# Events
# Repository realted
# events: push, pull_request, create, fork, watch
# issues, issues_comment, discussion...

# Other: workflow_dispatch, respository_dispatch, schedule, workflow_call

# ACTIONS
# Action: a third party app that runs commands and perform repetead tasks
# There're community and custom actions
# Actions are free in the market place

# Actions runs not on repo, that's why the code needs to be download (checkout)
# Checkout the documentation to see all events

# DEPENDENCIES
# The software used to run stuff has already intalled dependencies, like node for instance
name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code # getting the repo code
        uses: actions/checkout@v3 # uses is for using action only
        # with: # with to configure the action
      - name: Install NodeJS
        uses: actions/setup-node@3 # Already installed
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
