# Accessing metadata in Github
# Get context info and using expressions
name: 2 Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}" # Printing object to json
