# Matrix, allows to set multiple values
# Github Action will execute all combination set in the matrix
name: Matrix Demo
on:
  push:
jobs:
  build:
    continue-on-error: true # To keep executing even if some combination fail
    strategy:
      matrix:
        node-version: [14, 16]
        operation-system: [ubuntu-latest, windows-latest]
        # Using a single custom combinations
        inclue: 
          - node-version: 18
            operation-system: ubuntu-latest
        exclude:
          - node-version: 16
            operation-system: windows-latest
    runs-on: ${{ matrix.operation-system }} # Will run jobs in pararell with both os
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
