# Used from another workflow
name: 6.2 Reusable Workflow
on: 
  workflow_call: # Allows to be called from other workflow
    inputs: # Whatever you need and name
      artifact-name:
        description: The name of the artifact
        required: true
        type: string
        default: dist
    # Using passing back value as outputs
    outputs:
      result:
        description: The result of the operation
        value: ${{ jobs.deploy.outputs.outcome }} # Linking the output from deploy job
    # How to pass secrets
    # secrets:
    #   some-secrets:
    #     required: false
jobs:
  deploy:
    outputs:
      # Getting the value from set-result step as an output
      outcome: ${{ steps.set-result.outputs.set-result }} 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }} # Passing the value
      - name: Output Information
        run: echo "Deploying & Uploading"
      - name: Set result output # Storing the retrieving value to outout reusuable workflow
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT