name: My First Workflow
on: workflow_dispatch # Manually triggered
jobs:
  #custom job's name
  first-job:
   # Defined the runner 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World" 
      - name: Print good bye
        run: echo "Done... bye!"
